// ===== ПРОИЗВОДИТЕЛЬНОСТЬ ТРУДА =====
// Выручка на одного сотрудника (агрегированная)

Выручка_на_сотрудника = 
DIVIDE(
    SUM('Доходы_Все_Годы'[Доходы_тыс]),
    SUM('Chisl_Все_Годы'[Численность]),
    0
)
