// ===== ДОЛЯ УБЫТОЧНЫХ ОРГАНИЗАЦИЙ =====
// Показывает процент компаний, у которых расходы превышают доходы

Доля_Убыточных_2024 = 
DIVIDE(
    COUNTX(
        FILTER(
            'Доходы2024',
            'Доходы2024'[Доходы_тыс] < 'Доходы2024'[Расходы_тыс]
        ),
        'Доходы2024'[ИНН]
    ),
    DISTINCTCOUNT('Доходы2024'[ИНН]),
    0
) * 100
