// ===== РЕНТАБЕЛЬНОСТЬ =====
// Экономический смысл: отношение суммарной прибыли к суммарной выручке
// Агрегированный подход учитывает вес каждой организации

Рентабельность_2024 = 
DIVIDE(
    SUM('Доходы2024'[Доходы_тыс]) - SUM('Доходы2024'[Расходы_тыс]),
    SUM('Доходы2024'[Доходы_тыс]),
    0
)

// Динамическое переключение между годами
Рентабельность_Текущий = 
SWITCH(
    SELECTEDVALUE('Годы'[Год]),
    2024, [Рентабельность_2024],
    2023, [Рентабельность_2023],
    2022, [Рентабельность_2022],
    2021, [Рентабельность_2021],
    BLANK()
)

// Год-к-году (YoY) для анализа динамики
Рентабельность_YoY = 
VAR CurrentYear = [Рентабельность_Текущий]
VAR PreviousYear = 
    CALCULATE(
        [Рентабельность_Текущий],
        'Годы'[Год] = SELECTEDVALUE('Годы'[Год]) - 1
    )
RETURN
    DIVIDE(CurrentYear - PreviousYear, PreviousYear, 0)
