// ===== НАЛОГОВАЯ НАГРУЗКА =====
// Доля налогов в выручке (итоговая сумма без разбивки по видам)

Налоговая_Нагрузка = 
DIVIDE(
    SUM('Налоги_Все_Годы'[Сумма_налогов]),
    SUM('Доходы_Все_Годы'[Доходы_тыс]),
    0
)
